### ISSUE TITLE
Must disable Discord Handler if Discord Integration is disabled.

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#1]
How to reproduce:

- Associate your Discord ID with your profile
- Disable Discord Integration app
- Let Discord handler enabled (by default)
- Go to your user profile (in front-end), in Discord section.
- Click to disassociate
- An error is shown (A template is missing due to Discord app disabled)

**Comment by ABSAhmad** [comment]
"Fix" will be in the next version.
