### ISSUE TITLE
Error when Signing in

### ISSUE THREAD

**Issue by MayhemBill** [ABSAhmad/IpsDiscordIntegration#12]
Whenever I sign in, I get this issue: 
IPS\discord\Api\Exception\ForbiddenException:  (0)
#0 /var/www/html/applications/discord/sources/Api/AbstractResponse.php(64): IPS\discord\Api\_AbstractResponse->throwException('403')
#1 /var/www/html/applications/discord/sources/Api/GuildMember.php(57): IPS\discord\Api\_AbstractResponse->handleApi()
#2 /var/www/html/applications/core/sources/ProfileSync/Discord.php(63): IPS\discord\Api\_GuildMember->update(Object(IPS\Member))
#3 /var/www/html/applications/core/sources/ProfileSync/Discord.php(128): IPS\core\ProfileSync\_Discord->user()
#4 /var/www/html/system/Theme/Theme.php(780) : eval()'d code(6772): IPS\core\ProfileSync\_Discord->name()
#5 /var/www/html/system/Theme/SandboxedTemplate.php(57): IPS\Theme\class_core_front_system->settingsOverview(Array)
#6 /var/www/html/applications/core/modules/front/system/settings.php(148): IPS\Theme\_SandboxedTemplate->__call('settingsOvervie...', Array)
#7 [internal function]: IPS\core\modules\front\system\_settings->_overview()
#8 /var/www/html/applications/core/modules/front/system/settings.php(55): call_user_func(Array)
#9 /var/www/html/system/Dispatcher/Controller.php(97): IPS\core\modules\front\system\_settings->manage()
#10 /var/www/html/applications/core/modules/front/system/settings.php(35): IPS\Dispatcher\_Controller->execute()
#11 /var/www/html/system/Dispatcher/Dispatcher.php(129): IPS\core\modules\front\system\_settings->execute()
#12 /var/www/html/index.php(13): IPS\_Dispatcher->run()
#13 {main}

**Comment by itsAliAvali** [comment]
Which IPS version? 
Downloaded from Github or IPS Marketplace?
Is your bot's role on the top of the roles list in Discord?

**Comment by MayhemBill** [comment]
IPS is latest just before 4.2
Github
The bot didn't have a role, but now it does at the top

**Comment by itsAliAvali** [comment]
with the bot role (assigned to bot as well) now on top, does it work?

**Comment by MayhemBill** [comment]
Now I have a new error, which is a mismatched Redirect URI. Even though, the URI's are the ones I got from the settings panel

**Comment by itsAliAvali** [comment]
hmm. copy and pasted directly from the settings notification without any additional spaces at beginning or ending of the url?

**Comment by itsAliAvali** [comment]
![image](https://user-images.githubusercontent.com/2025022/28494013-5f44bc10-6ee7-11e7-80a5-a1a9426bc5e0.png)
and on two lines?

**Comment by MayhemBill** [comment]
Ah,  there was a space at the end of the auth.php one, and now I have a slightly different error than before, I get to this now:


IPS\discord\Api\Exception\ForbiddenException:  (0)
#0 /var/www/html/applications/discord/sources/Api/AbstractResponse.php(64): IPS\discord\Api\_AbstractResponse->throwException('403')
#1 /var/www/html/applications/discord/sources/Api/GuildMember.php(57): IPS\discord\Api\_AbstractResponse->handleApi()
#2 /var/www/html/system/Login/Discord.php(108): IPS\discord\Api\_GuildMember->update(Object(IPS\Member))
#3 /var/www/html/system/Login/Login.php(372): IPS\Login\_Discord->authenticate(Object(IPS\Http\Url\Friendly))
#4 /var/www/html/applications/core/modules/front/system/login.php(52): IPS\_Login->authenticate()
#5 /var/www/html/system/Dispatcher/Controller.php(97): IPS\core\modules\front\system\_login->manage()
#6 /var/www/html/system/Dispatcher/Dispatcher.php(129): IPS\Dispatcher\_Controller->execute()
#7 /var/www/html/index.php(13): IPS\_Dispatcher->run()
#8 {main}

**Comment by MayhemBill** [comment]
It seems the bot is also offline, on discord

**Comment by itsAliAvali** [comment]
the bot will appear offline in discord, but if you want to see it appear online briefly  press the handshake button in the ACP.

**Comment by MayhemBill** [comment]
Ah, the error is still the same as above.

**Comment by itsAliAvali** [comment]
API credentials entered correctly?

**Comment by MayhemBill** [comment]
Yes, they are, when I handshake it works correctly, bot comes online, I also double checked the creds are they're all correct. Would it matter if the bot had more permissions than it was assigned at the start?

**Comment by itsAliAvali** [comment]
nah, if it gets more permissions it shouldnt be a problem... for giggles try giving it the administrator permission flag. (administrator gives it all perms) if it works with that flag, it was just a permission setting error in discord.

**Comment by MayhemBill** [comment]
I've actually discovered that it isn't the highest on the discord list. But it's second highest, I didn't create the discord I cant move it. I was told it was given highest but I can do anything because that's the group I'm in. I'll have it moved up shortly hopefully

**Comment by Nebthtet** [comment]
I had that error unless the user on whose account the bot app has been created had admin privileges on Discord server.
So I advise trying to give permissions to your account (since you're the person who created the bot and to the bot itself.

**Comment by MayhemBill** [comment]
I have full permissions under the role I have, unless I need to have it specifically for me?

**Comment by itsAliAvali** [comment]
the bot having administrator should suffice ; the user who made the bot doesnt matter as the bot doesnt inherit their permissions or roles.
![image](https://user-images.githubusercontent.com/2025022/28494827-90554942-6eff-11e7-9f1b-4c289dc38e7a.png)

**Comment by MayhemBill** [comment]
I believe it is an issue with the bot being second on the list, and not at the very top, as I made the bot, and not the discord, I can't move it any higher than myself, which is where I believe the issue is arising. I have informed the creator of our discord, and he will hopefully be able to move it up.

**Comment by MayhemBill** [comment]
Okay, I got the bots role moved up top, and now it works just fine, no errors at all.

**Comment by itsAliAvali** [comment]
Glad to hear that @TheHeroBilly if this has been fully resolved for you, please click close issue.
