### ISSUE TITLE
[Suggestion] Updates and Releases

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#13]
Each version gets a [release](https://github.com/ABSAhmad/IpsDiscordIntegration/releases), that way the downloadable is already in discord.tar form  ; when you build the application you already have to get this file anyway for IPS MP. Makes it easier for versions.

Update the github to reflect latest version.

**Comment by ABSAhmad** [comment]
I will most likely use the releases from now on and also try to finish up the whole documentation using the GitHub wiki.

The source should always reflect the latest version (the master branch anyway) - if that is not the case, a push most likely failed or I simply forgot to push the code (you can send me a PM on IPS/email me/ping me on discord).
