### ISSUE TITLE
Invite members to discord.

### ISSUE THREAD

**Issue by ABSAhmad** [ABSAhmad/IpsDiscordIntegration#16]
Provide each member with a unique invite link to join the discord server.

**Comment by AileenLumina** [comment]
Isn't this a duplicate of #4? Anyways, it would be great if the admins could choose whether the invite is unique for each member, or if they want to define one that never expires. You could check the validity of that invite using the API.

**Comment by ABSAhmad** [comment]
I have decided to do this in a different way.

When a member links their discord account, they will be added into the guild automatically. They won't have to click on a link or anything.
