### ISSUE TITLE
Add icon to Discord Integration

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#2]
It could be great to add an icon on this handler,
I know that there is no Discord icon in Font Awesome,
But it could be replaced by fa-microphone or fa-headphone until next version 🎤 
This icon is used on front end / back end for login handler

**Comment by ABSAhmad** [comment]
A mic or headphone isn't really accurate either as discord is also a messenger.
The lock is fine for now, hopefully FA will add a discord icon soon. It's the most up-voted issue on their repo :)

**Comment by JigSawFr** [comment]
For reading purpose: https://github.com/FortAwesome/Font-Awesome/issues/7574
