### ISSUE TITLE
Corrupt or Invalid Application

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#20]
tried to run the update process on beta 2 to beta 3 from releases, and I get 

> 1C133/K The application you uploaded cannot be installed because it is not a valid application, the archive is corrupt or the file and directory permissions in /applications do not allow it.

I have also tried downloading the master and making my own .tar as previous install steps were; no change.

(also not a file/directory permission issue)

**Comment by ABSAhmad** [comment]
I cannot re-produce this issue.

However, I've attached the .tar file that I am using as a binary file on the release: https://github.com/ABSAhmad/IpsDiscordIntegration/releases/download/v1.1.0-beta.3/discord.tar.

You can try using that file.

**Comment by itsAliAvali** [comment]
that worked 👍
