### ISSUE TITLE
Discord Chat Widget

### ISSUE THREAD

**Issue by AileenLumina** [ABSAhmad/IpsDiscordIntegration#21]
To expand on #17, I think this application would gain a lot of relevance if there would be a way to connect the forums and the Discord server via a chat widget.
Some ideas I have for this:

- Cache messages using IPS' caching method
- In the widget, show IPS member link next to users' messages that are sent from Discord if the user linked their Discord account, otherwise display their nickname or username (could be a setting in the AdminCP)
- On Discord, use webhooks to send messages sent using the chat widget in order to be able to display the user's Discord avatar and nickname if they linked their Discord account, and if they didn't, use their IPS profile photo and display name

**Comment by ABSAhmad** [comment]
Sorry, but a chat widget will not be implemented.

To chat the users have to go and use discord's client.
