### ISSUE TITLE
Duplicate Members after editing them in AdminCP

### ISSUE THREAD

**Issue by defactofrank** [ABSAhmad/IpsDiscordIntegration#25]
With application* **disabled**:
Search member in AdminCP > Edit member > Save member > Search same member > Shows 1

With application* **enabled**:
Search member in AdminCP > Edit member > Save member > Search same member > Shows 2 (**duplicate created**)

No idea why, but for some reason it creates duplicates...
When either of the duplicate members is deleted (and content they created is kept), there doesn't seem to be any changes to the member or the created content.

Also, if any of the duplicated members are edited and saved again, it creates another duplicate (an infinite amount, if you wouldn't manually delete duplicates after editing those members)

_* = Discord Integration 1.2.0 Alpha 3 & Register Module_

**Comment by Eventyret** [comment]
This should be fixed in 4.2.2 (I believe it was a known bug) @deknarf

**Comment by ABSAhmad** [comment]
@deknarf Is this still happening with the latest IPS version?

**Comment by Eventyret** [comment]
Latest version was working for me. Though the one before it had this bug. Will try a clean install and report back.

**Comment by ThatGamerBlue** [comment]
still happens for me, v4.2.5

**Comment by ABSAhmad** [comment]
This should be fixed with the new Login Handler
