### ISSUE TITLE
4.2.2 No Settings

### ISSUE THREAD

**Issue by Eventyret** [ABSAhmad/IpsDiscordIntegration#26]
In the 4.2.2 there are no settings at all.
Tested on a fresh 4.2.2
![image](https://user-images.githubusercontent.com/977232/29187881-25e5f638-7e09-11e7-981b-0a4fef855df0.png)
Though it is shown in Account Settings.

**Comment by itsAliAvali** [comment]
@Eventyret you might be missing permissions to view and change settings for discord; as it appears you're missing clubs, thats where I got the idea of settings issue.

**Comment by Eventyret** [comment]
The reason I'm missing clubs is that I never activated it. That is just a fresh 4.2.2 install nothing done with configurations or anything.
Just installed 4.2.2 then added the plugin @madman32395

**Comment by ABSAhmad** [comment]
@Eventyret do you still have that problem? If yes, can you please email me ACP/FTP credentials?

**Comment by Eventyret** [comment]
Could close this i got it working after the last update and 4.2.4
