### ISSUE TITLE
Discord Bot and plugin no longer works. 

### ISSUE THREAD

**Issue by fifthmanstanding** [ABSAhmad/IpsDiscordIntegration#28]
As of yesterday our discord bot and this plugin ceased to work. The options are all still there on our admin cp but posts do not trigger the bot to post to the discord and the discord login option is not working and returns the following error: 

Sorry, there is a problem
Something went wrong. Please try again.
Error code: EX0

I made a post on your IPB support page here: https://invisioncommunity.com/forums/topic/435577-discord-integration/?page=10

**Comment by fifthmanstanding** [comment]
So at this juncture I've discovered that updating to 4.2 reset a lot of settings for the discord bot. I modified those settings to what they were originally and the bot is working. The only problem I have now is that discord login button still results in:

Sorry, there is a problem
Something went wrong. Please try again.
Error code: EX0

**Comment by ABSAhmad** [comment]
@fifthmanstanding can you please email ACP/FTP credentials?

**Comment by ABSAhmad** [comment]
This should already be fixed
