### ISSUE TITLE
Features suggestions - Feathub

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#3]
What do you think to add http://feathub.com to your repo ?
It could be great to suggest and vote for something (and not create an issue)

**Comment by ABSAhmad** [comment]
This may make sense for bigger repos, but for one that is as small as this one, it isn't really necessary. Creating an issue is fine for now.

**Comment by JigSawFr** [comment]
As you want, no problem ;)
