### ISSUE TITLE
Merge Users that have discord linked results in user being removed from discord

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#31]
Had a user that somehow registered two accounts that both had the same discord ID linked.. merged one of the accounts into the other that had purchases/ranks and in discord the user was removed with message saying user has left server.

**Comment by itsAliAvali** [comment]
unsure if its just merging in general though.

**Comment by ABSAhmad** [comment]
When merging a user, the one to be deleted gets kicked out of Discord. This was intentional, the new version will include more configuration options for that aspect.
