### ISSUE TITLE
Client ID phrasing / login handler

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#32]
I know its just phrasing, but would it be easier on the end user admin to have the wording the same as discord to help limit confusion during setup of the login handler?

ACP
![image](https://user-images.githubusercontent.com/2025022/45133675-2fb07080-b15c-11e8-88e9-c28959ca7764.png)
Discord Dev Page
![image](https://user-images.githubusercontent.com/2025022/45133685-3d65f600-b15c-11e8-815f-b7d9759cd3f6.png)

**Comment by ABSAhmad** [comment]
Those phrases are in the IPS core which I actually don't want to modify.
