### ISSUE TITLE
[Suggest] Auto-Generate Unique Invite Link

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#4]
It could be great to generate a unique link for our IPS community member (maye based on group) with a widget or a link somewhere.

With this we can run a Private Discord community.

1. Discord Server is private (No invitations link generated by default)
2. Member must register on IPS forum and associate his Discord ID (by login with on IPS)
3. After registration (and based on group the member is in), he can request a invitation link.
4. Discord integration will generate a unique Discord Invitation link for linked server (unique, one time, with expire date maybe) after checked that he is not already present.
5. Member will click on this link and will be invited to Discord Server
6. Invitation link will expire (one time invite)
7. Discord Integration will sync group for this member with IPS.
8. Done

What do you think ? :)

**Comment by JigSawFr** [comment]
Purpose of this request is:

- Have a private Discord Server with Invites Only (auto-generated)
- Allow only IPS members to be on Discord Server (auto-kick/ban others)
- One time management with synced roles/groups

**Comment by ABSAhmad** [comment]
Done in #16
