### ISSUE TITLE
[Suggest] Markdown Support

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#6]
Hello,
As Discord support Markdown,
It could be great that Discord Integration support it too,
We will be able to format text sent by bot.

Idea from: https://invisionpower.com/forums/topic/435577-discord-integration/?do=findComment&comment=2677600

**Comment by ABSAhmad** [comment]
The discord API does not support markdown except for basic stuff that you can currently already use (bold/italic/underline).

**Comment by itsAliAvali** [comment]
If they are talking about hyperlinks for text.... that's possible. 
![image](https://user-images.githubusercontent.com/2025022/28294949-fc77ba78-6b22-11e7-8b70-90bbde644609.png)
