### ISSUE TITLE
[Suggest] Shorten Links

### ISSUE THREAD

**Issue by JigSawFr** [ABSAhmad/IpsDiscordIntegration#7]
Hello,
Some members think that full URL's look long and messy,
Why not make them short b using a 3rd service like tinyurl?

Idea from: https://invisionpower.com/forums/topic/435577-discord-integration/?do=findComment&comment=2677600

**Comment by AileenLumina** [comment]
I think they look fine if you enable URL rewriting (and add some Friendly URLs if necessary). If this feature will be implemented, it should be optional, in my opinion. :)

**Comment by ABSAhmad** [comment]
Won't do, will use Discord embeds instead so the link shortening won't be necessary
